import { EXPO_PUBLIC_OPENAI_API_KEY, ENV_OPENAI_API_KEY, WAWA_OPENAI_API_KEY } from '@env';
// [WAWA_OPENAI_API_KEY, ENV_OPENAI_API_KEY, EXPO_PUBLIC_OPENAI_API_KEY];

export const OPENAI_API_KEY = (
  WAWA_OPENAI_API_KEY ||
  ENV_OPENAI_API_KEY ||
  EXPO_PUBLIC_OPENAI_API_KEY ||
  ''
).trim();
export const OPENAI_MODEL = 'gpt-5.4-mini';
