export const challengeTw = {
  screen: 'flex-1 bg-white',
  blackStatus: 'h-8 bg-black',
  shortBlackStatus: 'h-6 bg-black -mx-8',
  whiteTopSpacer: 'h-8 bg-white',

  topTargetBar: 'flex-row items-center bg-[#ece9e9] px-14 py-3',
  topTargetBarWide: 'flex-row items-center bg-[#ece9e9] px-16 py-3',
  targetThumb: 'h-24 w-24 overflow-hidden rounded-sm bg-neutral-100',
  targetPlaceholder: 'h-full w-full items-center justify-center',
  targetImage: 'h-full w-full',
  targetTextWrap: 'ml-10 flex-1',
  targetLabel: 'mb-3 text-xs font-extrabold uppercase text-slate-400',
  targetName: 'text-base font-bold text-black',
  targetNameWithButton: 'mb-3 text-base font-bold text-black',
  changeObjectButton: 'self-start rounded-full bg-neutral-300 px-4 py-3',
  changeObjectText: 'text-base text-black',

  challengeStartContent: 'min-h-full items-center bg-white px-8 pb-12 pt-8',
  challengeStartTitle: 'self-start text-xs font-extrabold uppercase tracking-widest text-slate-400',
  challengeStartTarget: 'mt-3 h-[320px] w-full overflow-hidden rounded-[22px] border-4 border-black bg-neutral-100',
  challengeStartHelp: 'mt-5 text-center text-base leading-6 text-slate-600',
  primaryButton: 'mt-6 h-14 w-full flex-row items-center justify-center gap-2 rounded-xl bg-black',
  primaryButtonText: 'text-lg font-bold text-white',
  secondaryButton: 'mt-3 h-14 w-full flex-row items-center justify-center gap-2 rounded-xl border border-slate-200 bg-slate-50',
  secondaryButtonText: 'text-lg font-bold text-black',

  captureBody: 'flex-1 items-center px-9 pt-4',
  cameraFrame: 'h-[424px] w-full max-w-[288px] overflow-hidden rounded-[22px] border-4 border-black bg-neutral-100',
  captureControls: 'mt-5 w-full max-w-[288px] flex-row items-center justify-between',
  roundIconButton: 'h-11 w-11 items-center justify-center rounded-full bg-neutral-200',
  shutterButton: 'h-[72px] w-[72px] items-center justify-center rounded-full border-4 border-black bg-neutral-300',
  shutterInner: 'h-[58px] w-[58px] rounded-full bg-neutral-300',
  permissionScreen: 'flex-1 items-center justify-center bg-white px-8',
  permissionIcon: 'mb-3 text-5xl',
  permissionTitle: 'mb-2 text-xl font-bold text-black',
  permissionText: 'mb-7 text-center text-sm text-neutral-500',
  permissionButton: 'rounded-full bg-neutral-300 px-6 py-3',
  permissionButtonText: 'text-base text-black',

  comparingBody: 'flex-1 items-center px-9 pt-4',
  comparingCandidateImage: 'h-full w-full',
  comparingFallback: 'h-full w-full items-center justify-center',
  scanBand: 'absolute left-0 right-0 h-16 bg-white/35',
  scanPulse: 'absolute left-8 right-8 top-1/2 h-24 rounded-full bg-white/40',
  scanBorder: 'absolute inset-0 border-2 border-white/25',
  comparingText: 'mt-5 text-2xl font-medium text-neutral-800',

  resultContent: 'min-h-full px-8 pb-12',
  shareWrap: 'items-end pt-3',
  shareButton: 'flex-row items-center gap-2',
  shareText: 'text-sm text-black',
  resultCenter: 'mt-6 items-center',
  wrongResultCenter: 'items-center pt-16',
  uniCircle: 'h-48 w-48 items-center justify-center rounded-full bg-slate-100',
  uniFace: 'h-[72px] w-[72px] items-center justify-center rounded-full bg-slate-400',
  sadFaceWrap: 'items-center',
  sadLabel: 'mt-3 text-[10px] uppercase tracking-widest text-slate-500',
  levelText: 'mt-5 text-base font-bold text-black',
  xpCard: 'mt-4 w-full rounded-xl bg-neutral-500 px-4 py-4',
  xpHeader: 'mb-2 flex-row justify-between',
  xpLabel: 'text-sm font-bold text-white',
  xpValue: 'text-sm text-white',
  xpTrack: 'h-3 overflow-hidden rounded-full bg-slate-100',
  xpFill: 'h-full w-[70%] rounded-full bg-neutral-700',
  successTitle: 'mt-7 text-center text-[30px] font-normal leading-9 text-black',
  wrongTitle: 'mt-12 text-center text-[31px] font-normal text-black',
  resultCopy: 'mt-3 text-center text-[17px] leading-6 text-slate-600',
  wrongCopy: 'mt-5 text-center text-[17px] leading-6 text-slate-600',
  resultButton: 'mt-6 h-14 w-full items-center justify-center rounded-xl bg-black',
  resultButtonText: 'text-lg font-bold text-white',
  emergencyButton: 'mt-2 h-14 w-full items-center justify-center rounded-xl border border-slate-200 bg-slate-50',
  emergencyText: 'text-lg font-bold text-black',

  streakCard: 'mt-8 w-[92%] rounded-3xl bg-slate-900 px-6 py-7',
  streakHeader: 'flex-row items-center justify-center',
  streakCount: 'ml-3 text-4xl font-light text-white',
  streakLabel: 'mt-2 text-center text-xs uppercase tracking-widest text-slate-400',
  streakDays: 'mt-6 flex-row justify-between',
  streakDayDone: 'h-6 w-6 items-center justify-center rounded-full bg-white',
  streakDayEmpty: 'h-6 w-6 items-center justify-center rounded-full bg-slate-700',

  emptyScreen: 'flex-1 items-center justify-center bg-white px-8',
  emptyIcon: 'mb-4 text-6xl',
  emptyTitle: 'mb-2 text-xl font-bold text-black',
  emptyText: 'text-center text-sm text-slate-500',
  errorScreen: 'flex-1 items-center justify-center bg-white px-8',
  errorTitle: 'mt-3 text-lg font-bold text-black',
  errorMessage: 'mt-2 text-center text-sm text-slate-500',
} as const;
